<?xml version="1.0" encoding="UTF-8" ?>

          <!-- Internal DTD -->
          <!DOCTYPE coverage [
          <!-- Portions (C) International Organization for Standardization 1986:
          Permission to copy in any form is granted for use with
          conforming SGML systems and applications as defined in
          ISO 8879, provided this notice is included in all copies.
          -->

          <!ELEMENT coverage (sources?,packages)>
          <!ATTLIST coverage line-rate   CDATA #REQUIRED>
          <!ATTLIST coverage branch-rate CDATA #REQUIRED>
          <!ATTLIST coverage version     CDATA #REQUIRED>
          <!ATTLIST coverage timestamp   CDATA #REQUIRED>

          <!ELEMENT sources (source*)>

          <!ELEMENT source (#PCDATA)>

          <!ELEMENT packages (package*)>

          <!ELEMENT package (classes)>
          <!ATTLIST package name        CDATA #REQUIRED>
          <!ATTLIST package line-rate   CDATA #REQUIRED>
          <!ATTLIST package branch-rate CDATA #REQUIRED>
          <!ATTLIST package complexity  CDATA #REQUIRED>

          <!ELEMENT classes (class*)>

          <!ELEMENT class (methods,lines)>
          <!ATTLIST class name        CDATA #REQUIRED>
          <!ATTLIST class filename    CDATA #REQUIRED>
          <!ATTLIST class line-rate   CDATA #REQUIRED>
          <!ATTLIST class branch-rate CDATA #REQUIRED>
          <!ATTLIST class complexity  CDATA #REQUIRED>

          <!ELEMENT methods (method*)>

          <!ELEMENT method (lines)>
          <!ATTLIST method name        CDATA #REQUIRED>
          <!ATTLIST method signature   CDATA #REQUIRED>
          <!ATTLIST method line-rate   CDATA #REQUIRED>
          <!ATTLIST method branch-rate CDATA #REQUIRED>

          <!ELEMENT lines (line*)>

          <!ELEMENT line (conditions*)>
          <!ATTLIST line number CDATA #REQUIRED>
          <!ATTLIST line hits   CDATA #REQUIRED>
          <!ATTLIST line branch CDATA "false">
          <!ATTLIST line condition-coverage CDATA "100%">

          <!ELEMENT conditions (condition*)>

          <!ELEMENT condition EMPTY>
          <!ATTLIST condition number CDATA #REQUIRED>
          <!ATTLIST condition type CDATA #REQUIRED>
          <!ATTLIST condition coverage CDATA #REQUIRED>
          ]>
<coverage line-rate="0.4" branch-rate="0" version="2.1.0" timestamp="2016-06-23 22:03:40">
  <sources>
    <source>R/TestSummary.R</source>
  </sources>
  <packages>
    <package name="TestSummary" line-rate="0.4" branch-rate="0" complexity="0">
      <classes>
        <class name="TestSummary.R" filename="R/TestSummary.R" line-rate="0.4" branch-rate="0" complexity="0">
          <methods>
            <method name="test_me" signature="NA" line-rate="0.5" branch-rate="0">
              <lines>
                <line number="5" hits="1" branch="false"/>
                <line number="6" hits="1" branch="false"/>
                <line number="7" hits="0" branch="false"/>
                <line number="8" hits="0" branch="false"/>
              </lines>
            </method>
            <method name="dont_test_me" signature="NA" line-rate="0" branch-rate="0">
              <lines>
                <line number="13" hits="0" branch="false"/>
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="1" branch="false"/>
            <line number="6" hits="1" branch="false"/>
            <line number="7" hits="0" branch="false"/>
            <line number="8" hits="0" branch="false"/>
            <line number="13" hits="0" branch="false"/>
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
